parameters:
    app_directory_len: 4
services:
    app.repository.category:
        class:            AppBundle\Repository\CategoryRepository
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:        ['AppBundle:Category']

    app.repository.subcategory:
        class: AppBundle\Repository\SubCategoryRepository
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:        ['AppBundle:Subcategory']

    app.repository.photo:
        class: AppBundle\Repository\PhotoRepository
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:        ['AppBundle:Photo']

    app.naming.tree_directory:
        class: AppBundle\Naming\TreeDirectoryNaming
        arguments: [ %app_directory_len% ]